version: 0.0
os: linux
files:
  - source: /frontend
    destination: /var/www/business.interninit.com
  - source: /backend
    destination: /home/ubuntu/FLASKAPPS/backend
hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/pip-setup
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
