version: 0.2

phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
      - cp $CODEBUILD_SRC_DIR_S3SourceArtifact/cognito-config.json ./src/config/cognito-config.json
      - cp $CODEBUILD_SRC_DIR_S3SourceArtifact/network-config.json ./backend/config/network-config.json
  build:
    commands:
      - echo Building...
      - npm run build
  post_build:
    commands:
      - mkdir ./fullbuild
      - cp -a ./build ./fullbuild/frontend
      - cp -a ./backend ./fullbuild/backend
      - mv ./fullbuild/backend/__init__.py ./fullbuild/backend/backend.py
      - cp ./requirements.txt ./fullbuild/backend/requirements.txt
      - cp ./appspec.yml ./fullbuild/appspec.yml
      - cp -a ./scripts ./fullbuild/scripts
      - cp -a ./apache ./fullbuild/apache
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: fullbuild
