#!/bin/bash
if [ -d "/var/www/business.interninit.com" ]; then
    rm -rf /var/www/business.interninit.com/*
    rm -rf /var/www/business.interninit.com/.[a-zA-Z_]*
fi

if [ -d "/home/ubuntu/FLASKAPPS/backend" ]; then
    rm -rf /home/ubuntu/FLASKAPPS/backend/*
    rm -rf /home/ubuntu/FLASKAPPS/backend/.[a-zA-Z_]*
fi

if [ -d "/var/www/html" ]; then
    rm -rf /var/www/html
fi