#!/bin/bash
rm -rf /home/bitnami/apps/business-portal/htdocs/{,.[!.],..?}*
rm -rf /home/bitnami/FLASKAPPS/bp-backend/{,.[!.],..?}*

source /home/bitnami/FLASKAPPS/env/activate
pip install -r requirements.txt
deactivate