/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3c38mBd7B",
    "aws_user_pools_web_client_id": "791rbu1epi58cc7pvf5hc7jn25",
    "oauth": {}
};


export default awsmobile;
